from typing import List, Dict, Optional
import json
import os
import re

from database import get_connection


# =========================================================
# ACTION CATALOG
# =========================================================
#
# IMPORTANT:
# The business-specific actions are NOT stored in this file.
#
# They are loaded from:
#
#     actions_config.json
#
# This keeps the engine generic while preserving the
# existing ACTIONS variable for backward compatibility.
# =========================================================

DEFAULT_ACTION_CONFIG = "actions_config.json"


def load_action_catalog(
    config_path: str = DEFAULT_ACTION_CONFIG
) -> Dict:
    """
    Load business-specific actions from an external JSON file.

    The engine itself does not know which KPIs a business has.
    """

    if not os.path.exists(config_path):
        print(
            f"Warning: action configuration file "
            f"'{config_path}' was not found."
        )

        return {}

    try:

        with open(
            config_path,
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

        if not isinstance(data, dict):

            print(
                "Warning: action configuration must "
                "contain a JSON object."
            )

            return {}

        return data

    except json.JSONDecodeError as e:

        print(
            f"Warning: Invalid JSON in "
            f"'{config_path}': {e}"
        )

        return {}

    except OSError as e:

        print(
            f"Warning: Could not read "
            f"'{config_path}': {e}"
        )

        return {}


# =========================================================
# BACKWARD-COMPATIBILITY ACTIONS VARIABLE
# =========================================================
#
# Existing code such as:
#
#     from action_engine import ACTIONS
#
# continues to work.
#
# But ACTIONS is now loaded from external configuration.
# =========================================================

ACTIONS = load_action_catalog()


# =========================================================
# ACTION ID GENERATOR
# =========================================================

def create_action_id(
    action_name: str
) -> str:
    """
    Generate a stable ID from an action description.

    Example:

        Review marketing channel performance

    becomes:

        review_marketing_channel_performance
    """

    action_id = str(
        action_name
    ).lower()

    action_id = re.sub(
        r"[^a-z0-9]+",
        "_",
        action_id
    )

    return action_id.strip("_")


# =========================================================
# GENERATE ACTIONS
# =========================================================

def generate_actions(
    kpi: str
) -> List[Dict]:
    """
    Return actions associated with a KPI.

    The KPI itself is NOT hard-coded here.
    It is simply used as a lookup key into the
    externally loaded action catalog.

    Existing callers can continue using:

        generate_actions("revenue")
    """

    if not kpi:

        return []


    normalized_kpi = str(
        kpi
    ).strip().lower()


    actions = ACTIONS.get(
        normalized_kpi,
        []
    )


    result = []


    for action in actions:

        if not isinstance(action, dict):

            continue


        action_copy = action.copy()


        # ---------------------------------------------
        # Generate an ID automatically if configuration
        # did not explicitly provide one.
        # ---------------------------------------------

        if not action_copy.get("id"):

            action_copy["id"] = create_action_id(

                action_copy.get(
                    "action",
                    "unknown_action"
                )
            )


        result.append(
            action_copy
        )


    return result


# =========================================================
# MERGE LLM ACTIONS
# =========================================================

def merge_llm_actions(
    rule_based: List[Dict],
    llm_actions: Optional[List[Dict]]
) -> List[Dict]:
    """
    Merge deterministic/configured actions with
    situation-specific actions generated by the LLM.

    Existing rule-based actions remain available even
    when the LLM produces nothing.
    """

    if not llm_actions:

        merged = []

        for action in rule_based:

            action_copy = action.copy()

            action_copy.setdefault(
                "source",
                "rule_based"
            )

            merged.append(
                action_copy
            )

        return merged


    merged = []


    existing_ids = set()


    # -----------------------------------------------------
    # Add rule-based actions first
    # -----------------------------------------------------

    for action in rule_based:

        action_copy = action.copy()

        action_id = action_copy.get(
            "id"
        )


        if not action_id:

            action_id = create_action_id(
                action_copy.get(
                    "action",
                    "unknown_action"
                )
            )

            action_copy["id"] = action_id


        action_copy.setdefault(
            "source",
            "rule_based"
        )


        if action_id not in existing_ids:

            merged.append(
                action_copy
            )

            existing_ids.add(
                action_id
            )


    # -----------------------------------------------------
    # Add LLM actions
    # -----------------------------------------------------

    for index, action in enumerate(
        llm_actions
    ):

        if not isinstance(action, dict):

            continue


        action_copy = action.copy()


        action_id = action_copy.get(
            "id"
        )


        if not action_id:

            action_id = create_action_id(
                action_copy.get(
                    "action",
                    f"llm_generated_{index}"
                )
            )


            if not action_id:

                action_id = (
                    f"llm_generated_{index}"
                )


            # Prevent collision with existing
            # deterministic actions.
            if action_id in existing_ids:

                action_id = (
                    f"llm_{index}_{action_id}"
                )


            action_copy["id"] = action_id


        action_copy["source"] = "llm"


        if action_id not in existing_ids:

            merged.append(
                action_copy
            )

            existing_ids.add(
                action_id
            )


    return merged


# =========================================================
# HISTORICAL ACTION SCORES
# =========================================================

def get_historical_scores(
    kpi: Optional[str] = None
) -> Dict[str, float]:
    """
    Return:

        {
            action_id: historical_score
        }

    from analyst feedback stored in PostgreSQL.

    Score consists of:

        60% analyst rating
        40% actual outcome

    The score is then shrunk toward 0.5 when there are
    only a small number of observations.

    Existing /actions/scores and /root-cause code
    can continue using this function unchanged.
    """

    query = """
        SELECT
            action_id,

            AVG(analyst_rating) AS avg_rating,

            AVG(
                CASE outcome

                    WHEN 'positive'
                        THEN 1.0

                    WHEN 'negative'
                        THEN 0.0

                    ELSE 0.5

                END
            ) AS outcome_score,

            COUNT(*) AS n

        FROM business_decisions

        WHERE action_id IS NOT NULL

        {kpi_filter}

        GROUP BY action_id
    """


    kpi_filter = (
        "AND LOWER(kpi) = %s"
        if kpi
        else ""
    )


    query = query.format(
        kpi_filter=kpi_filter
    )


    connection = None
    cursor = None


    try:

        connection = get_connection()

        cursor = connection.cursor()


        if kpi:

            cursor.execute(
                query,
                (
                    str(kpi)
                    .strip()
                    .lower(),
                )
            )

        else:

            cursor.execute(
                query
            )


        rows = cursor.fetchall()


    except Exception as e:

        print(
            f"Warning: Could not retrieve "
            f"historical action scores: {e}"
        )

        return {}


    finally:

        if cursor is not None:

            try:
                cursor.close()
            except Exception:
                pass


        if connection is not None:

            try:
                connection.close()
            except Exception:
                pass


    scores = {}


    for (
        action_id,
        avg_rating,
        outcome_score,
        n
    ) in rows:

        # ---------------------------------------------
        # Safe defaults
        # ---------------------------------------------

        avg_rating = (

            float(avg_rating)

            if avg_rating is not None

            else 3.0
        )


        outcome_score = (

            float(outcome_score)

            if outcome_score is not None

            else 0.5
        )


        n = int(n or 0)


        # ---------------------------------------------
        # Analyst rating:
        #
        # 1-5 -> 0-1
        # ---------------------------------------------

        rating_component = (

            avg_rating - 1
        ) / 4


        rating_component = max(
            0.0,
            min(
                1.0,
                rating_component
            )
        )


        # ---------------------------------------------
        # Historical blended score
        # ---------------------------------------------

        blended = (

            0.6 * rating_component

            +

            0.4 * outcome_score
        )


        # ---------------------------------------------
        # Confidence based on observation count
        # ---------------------------------------------

        confidence = min(
            n / 10,
            1.0
        )


        # ---------------------------------------------
        # Shrink toward neutral 0.5
        # ---------------------------------------------

        score = (

            0.5

            +

            confidence *
            (blended - 0.5)
        )


        scores[str(action_id)] = round(
            score,
            3
        )


    return scores


# =========================================================
# RANK ACTIONS
# =========================================================

def rank_actions(
    actions: List[Dict],
    historical_scores: Optional[Dict[str, float]] = None
) -> List[Dict]:
    """
    Rank actions according to historical feedback.

    Actions without historical data receive 0.5.

    This function does NOT care which KPIs or business
    domain the actions belong to.
    """

    if historical_scores is None:

        historical_scores = {}


    ranked = []


    for action in actions:

        result = action.copy()


        # -------------------------------------------------
        # Prefer stable action ID
        # -------------------------------------------------

        action_id = result.get(
            "id"
        )


        if not action_id:

            action_id = create_action_id(
                result.get(
                    "action",
                    "unknown_action"
                )
            )

            result["id"] = action_id


        # -------------------------------------------------
        # Historical score
        # -------------------------------------------------

        score = historical_scores.get(
            action_id,
            0.5
        )


        result["score"] = round(
            float(score),
            3
        )


        ranked.append(
            result
        )


    # -----------------------------------------------------
    # Highest score first
    # -----------------------------------------------------

    ranked.sort(

        key=lambda item:
            item.get(
                "score",
                0.5
            ),

        reverse=True
    )


    return ranked